// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmfCOi9OLO-MHrkAPr2f3IMHeitV_CZHQ',
    appId: '1:827300633323:web:a3c96882a55aa29d54bcae',
    messagingSenderId: '827300633323',
    projectId: 'protectme-78834',
    authDomain: 'protectme-78834.firebaseapp.com',
    storageBucket: 'protectme-78834.firebasestorage.app',
    measurementId: 'G-B6N15JSMED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjQTcCa7Fy9oldtrsobE0INoamLNtjT60',
    appId: '1:827300633323:android:9e12e3f7b73254c554bcae',
    messagingSenderId: '827300633323',
    projectId: 'protectme-78834',
    storageBucket: 'protectme-78834.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLRK-1IWKE_12wl1c2P7NhjmHBRgq_0B0',
    appId: '1:827300633323:ios:3da8a17048019fa154bcae',
    messagingSenderId: '827300633323',
    projectId: 'protectme-78834',
    storageBucket: 'protectme-78834.firebasestorage.app',
    iosBundleId: 'com.example.protect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLRK-1IWKE_12wl1c2P7NhjmHBRgq_0B0',
    appId: '1:827300633323:ios:3da8a17048019fa154bcae',
    messagingSenderId: '827300633323',
    projectId: 'protectme-78834',
    storageBucket: 'protectme-78834.firebasestorage.app',
    iosBundleId: 'com.example.protect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmfCOi9OLO-MHrkAPr2f3IMHeitV_CZHQ',
    appId: '1:827300633323:web:66aa6383426e883154bcae',
    messagingSenderId: '827300633323',
    projectId: 'protectme-78834',
    authDomain: 'protectme-78834.firebaseapp.com',
    storageBucket: 'protectme-78834.firebasestorage.app',
    measurementId: 'G-C23HMT7W9C',
  );

}